-- ============================================================
-- POSシステム 正スキーマ（2026-07-22 全面刷新）
-- 新規環境はこのファイルを Supabase SQL Editor で実行すれば構築できる。
-- 既存環境への適用履歴は supabase/migrations/ を参照。
--
-- 構成:
--   マスタ   : stores / products / coupons
--   レイアウト: blocks / layout_elements
--   売上系   : sessions / payments / daily_expenses
-- ============================================================

-- ── stores: 店舗マスタ（設定値も店舗ごとに持つ） ─────────────────────
CREATE TABLE IF NOT EXISTS stores (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  business_day_start_time TIME NOT NULL DEFAULT '18:00',
  tax_rate REAL NOT NULL DEFAULT 10,
  checked_out_display_seconds INTEGER NOT NULL DEFAULT 10,
  pin_hash TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ── products: 商品マスタ ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  store_id BIGINT NOT NULL DEFAULT 1 REFERENCES stores(id),
  category TEXT NOT NULL DEFAULT '',
  subcategory TEXT,
  item_name TEXT NOT NULL,
  price_yen INTEGER NOT NULL DEFAULT 0,
  is_active BOOLEAN NOT NULL DEFAULT true,
  display_order INTEGER NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_products_store ON products (store_id, display_order);

-- ── coupons: クーポンマスタ ──────────────────────────────────────────
CREATE TABLE IF NOT EXISTS coupons (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  store_id INTEGER NOT NULL DEFAULT 1 REFERENCES stores(id),
  name TEXT NOT NULL,
  discount_type TEXT NOT NULL,
  discount_value REAL NOT NULL,
  valid_from TEXT,
  valid_to TEXT,
  is_active BOOLEAN NOT NULL DEFAULT true
);

-- ── blocks: 卓・レーンなどのサービスブロック（配置含む） ─────────────
CREATE TABLE IF NOT EXISTS blocks (
  id TEXT PRIMARY KEY,
  store_id BIGINT NOT NULL DEFAULT 1 REFERENCES stores(id),
  name TEXT NOT NULL,
  block_type TEXT NOT NULL,
  x REAL NOT NULL,
  y REAL NOT NULL,
  width REAL NOT NULL,
  height REAL NOT NULL,
  rotation REAL NOT NULL DEFAULT 0,
  status TEXT NOT NULL DEFAULT 'empty',
  capacity INTEGER NOT NULL DEFAULT 1,
  started_at TIMESTAMPTZ,
  checked_out_at TIMESTAMPTZ
);

-- ── layout_elements: 装飾用レイアウト要素（壁・入口など） ────────────
CREATE TABLE IF NOT EXISTS layout_elements (
  id TEXT PRIMARY KEY,
  store_id BIGINT NOT NULL DEFAULT 1 REFERENCES stores(id),
  type TEXT NOT NULL,
  x REAL NOT NULL,
  y REAL NOT NULL,
  width REAL NOT NULL,
  height REAL NOT NULL,
  rotation REAL NOT NULL DEFAULT 0,
  label TEXT
);

-- ── sessions: 接客セッション（注文明細は order_items JSONB に内包） ──
CREATE TABLE IF NOT EXISTS sessions (
  id TEXT PRIMARY KEY,
  store_id BIGINT NOT NULL DEFAULT 1 REFERENCES stores(id),
  block_id TEXT NOT NULL,
  linked_block_ids TEXT[],
  order_items JSONB NOT NULL DEFAULT '[]'::jsonb,
  started_at TIMESTAMPTZ NOT NULL,
  ended_at TIMESTAMPTZ,
  guest_count INTEGER NOT NULL DEFAULT 1,
  note TEXT,
  customer_name TEXT,
  happy_hour BOOLEAN NOT NULL DEFAULT false
);
CREATE INDEX IF NOT EXISTS idx_sessions_store ON sessions (store_id);

-- ── payments: 会計（アプリが "pay-<timestamp>" 形式のTEXT IDを発行） ─
CREATE TABLE IF NOT EXISTS payments (
  id TEXT PRIMARY KEY,
  store_id BIGINT NOT NULL DEFAULT 1 REFERENCES stores(id),
  session_id TEXT NOT NULL,
  block_id TEXT NOT NULL,
  payment_datetime TIMESTAMPTZ NOT NULL,
  business_date TEXT NOT NULL,
  subtotal_amount INTEGER NOT NULL,
  discount_amount INTEGER NOT NULL DEFAULT 0,
  tax_amount INTEGER NOT NULL DEFAULT 0,
  total_amount INTEGER NOT NULL,
  cash_amount INTEGER NOT NULL DEFAULT 0,
  cashless_amount INTEGER NOT NULL DEFAULT 0,
  guest_count INTEGER NOT NULL DEFAULT 1,
  note TEXT,
  canceled_at TIMESTAMPTZ,
  cancel_reason TEXT,
  paid_item_ids JSONB,
  coupon_id TEXT,
  customer_name TEXT,
  session_started_at TIMESTAMPTZ,
  synced_to_sheet_at TIMESTAMPTZ,
  square_payment_id TEXT
);
CREATE INDEX IF NOT EXISTS idx_payments_store_date ON payments (store_id, business_date);
CREATE INDEX IF NOT EXISTS idx_payments_unsynced ON payments (store_id)
  WHERE synced_to_sheet_at IS NULL AND canceled_at IS NULL;

-- ── daily_expenses: 日次経費（店舗×営業日で1行） ─────────────────────
CREATE TABLE IF NOT EXISTS daily_expenses (
  store_id BIGINT NOT NULL DEFAULT 1 REFERENCES stores(id),
  business_date TEXT NOT NULL,
  receipt_count INTEGER NOT NULL DEFAULT 0,
  amount INTEGER NOT NULL DEFAULT 0,
  handover_note TEXT NOT NULL DEFAULT '',
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (store_id, business_date)
);

-- ============================================================
-- RLS（Row Level Security）
-- アプリは anon キーで全操作（店内POS専用）。GAS は service_role でバイパス。
-- ============================================================

ALTER TABLE stores          ENABLE ROW LEVEL SECURITY;
ALTER TABLE products        ENABLE ROW LEVEL SECURITY;
ALTER TABLE coupons         ENABLE ROW LEVEL SECURITY;
ALTER TABLE blocks          ENABLE ROW LEVEL SECURITY;
ALTER TABLE layout_elements ENABLE ROW LEVEL SECURITY;
ALTER TABLE sessions        ENABLE ROW LEVEL SECURITY;
ALTER TABLE payments        ENABLE ROW LEVEL SECURITY;
ALTER TABLE daily_expenses  ENABLE ROW LEVEL SECURITY;

CREATE POLICY anon_all ON stores          FOR ALL TO anon USING (true) WITH CHECK (true);
CREATE POLICY anon_all ON products        FOR ALL TO anon USING (true) WITH CHECK (true);
CREATE POLICY anon_all ON coupons         FOR ALL TO anon USING (true) WITH CHECK (true);
CREATE POLICY anon_all ON blocks          FOR ALL TO anon USING (true) WITH CHECK (true);
CREATE POLICY anon_all ON layout_elements FOR ALL TO anon USING (true) WITH CHECK (true);
CREATE POLICY anon_all ON sessions        FOR ALL TO anon USING (true) WITH CHECK (true);
CREATE POLICY anon_all ON payments        FOR ALL TO anon USING (true) WITH CHECK (true);
CREATE POLICY anon_all ON daily_expenses  FOR ALL TO anon USING (true) WITH CHECK (true);

-- ============================================================
-- Realtime（他端末へのリアルタイム反映）
-- ============================================================

ALTER PUBLICATION supabase_realtime ADD TABLE stores;
ALTER PUBLICATION supabase_realtime ADD TABLE products;
ALTER PUBLICATION supabase_realtime ADD TABLE coupons;
ALTER PUBLICATION supabase_realtime ADD TABLE blocks;
ALTER PUBLICATION supabase_realtime ADD TABLE layout_elements;
ALTER PUBLICATION supabase_realtime ADD TABLE sessions;
ALTER PUBLICATION supabase_realtime ADD TABLE payments;
ALTER PUBLICATION supabase_realtime ADD TABLE daily_expenses;

-- RLS 有効テーブルで postgres_changes を受信するために必須
ALTER TABLE stores          REPLICA IDENTITY FULL;
ALTER TABLE products        REPLICA IDENTITY FULL;
ALTER TABLE coupons         REPLICA IDENTITY FULL;
ALTER TABLE blocks          REPLICA IDENTITY FULL;
ALTER TABLE layout_elements REPLICA IDENTITY FULL;
ALTER TABLE sessions        REPLICA IDENTITY FULL;
ALTER TABLE payments        REPLICA IDENTITY FULL;
ALTER TABLE daily_expenses  REPLICA IDENTITY FULL;

-- ── 初期データ（新規環境のみ） ───────────────────────────────────────
INSERT INTO stores (id, name) VALUES (1, 'ゆとり') ON CONFLICT (id) DO NOTHING;
