-- 商品の並び順を1回の upsert でまとめて保存できるようにする。
--
-- products.id は GENERATED ALWAYS AS IDENTITY だったため、upsert（内部は
-- INSERT ... ON CONFLICT）が明示的な id を拒否し（SQLSTATE 428C9）、
-- 並び替えの保存が必ず失敗していた。
-- BY DEFAULT にすると、id を省いた通常の INSERT（商品追加）はこれまでどおり
-- 採番され、id を指定した upsert も通るようになる。
ALTER TABLE products ALTER COLUMN id SET GENERATED BY DEFAULT;
